Hajuuu/MoneyLog

moneyLog/package.json

- <package.json>: <axio,fontawesome,bootstrap 의존성 추가>

fix: package.json axios,font-awesome, bootstrap 의존성 추가

---

package-lock.json
package.json
src/App.vue
src/assets/main.css
src/components/BottomNav.vue
src/main.js
src/pages/HomePage.vue
src/router/index.js

package.json
src/App.vue  : div 클래스 추가 (큰 틀 구역지정),  main.css import
src/assets/main.css (bootstrap, font awesome import)
src/main.js (main.css import 를 App.vue 로 이동)

Feat : 기본 골격 수정

---

src/components/BottomNav.vue
src/pages/GoalPage.vue
src/pages/HomePage.vue
src/pages/SettingImgPage.vue
src/pages/SettingPage.vue
src/pages/SettingProfilePage.vue
src/pages/StatisticsPage.vue
src/pages/TransactionsPage.vue
src/router/index.js

- 하단 네비게이션바 라우트 설정
- 라우터 경로 설정 및 추가
- 통계, 목표, 설정페이지 골격 생성
Related to #10

Feat: 페이지 기초 틀 생성, 전반적 라우트 경로 설정

---

src/api/index.js
src/stores/budget.js
src/stores/goal.js
src/stores/setting.js

- index.js: axios 연결
- budget.js: budget store 정의
- setting.js: setting store 정의
- goal.js: goal store 정의
- axios를 연결하고 store를 정의했습니다.
- #

feat: store 정의 및 axios 연결

---

src/pages/HomePage.vue

feat: store 적용

---

src/stores/budget.js

feat: monthlyExpense 로직 구현

---

src/api/index.js
src/pages/SettingImgPage.vue
src/pages/SettingPage.vue
src/pages/SettingProfilePage.vue

- <src/api/index.js>: <db 연결>
- <src/pages/SettingImgPage.vue>: <db 연결>
- <src/pages/SettingPage.vue>: <db 연결>
db 연결
#18 
#17

feat: index, setting page db연결

---

src/components/AddTransactionModal.vue
src/pages/HomePage.vue

- 신규 거래 추가 모달창 추가 완료
components/AddTransactionModal.vue
- HomePage.vue 날짜 선택기 추가,  모달창 출력되게 등 완료
- 
-

Feat : 홈페이지 기능 추가, 신규거래모달창 완료

---

src/pages/SettingImgPage.vue
src/pages/SettingPage.vue
src/pages/SettingProfilePage.vue
src/stores/setting.js

- [SettingImgPage pinia 연결]: <변경 내용>
- [SettingPage pinia 연결]: <변경 내용>
- [SettingProfilePage pinia 연결]: <변경 내용>
#18

feat:setting, UI로직 수정

---

src/pages/DetailPage.vue
src/pages/HomePage.vue
src/pages/TransactionsPage.vue
src/router/index.js
src/stores/budget.js

feat: 거래 상세 페이지 구현

---

src/pages/StatisticsPage.vue

feat: 데이터베이스 연동헀습니다

---

src/components/CalanderView.vue
src/main.js

feat: main.js v-calender임포트, CalanderView컴포넌트 추가

---

package-lock.json
package.json

feat: package.json v-calender 추가

---

src/stores/budget.js

feat: 현재 목표 금액 계산 로직 구현

---

src/components/TransactionListView.vue
src/pages/DetailPage.vue
src/pages/MonthlyTransactionsPage.vue
src/pages/TransactionsPage.vue
src/router/index.js

- 거래내역 목록클릭시 상세정보 이동 구현
- 상세정보 화면 구현(수정, 삭제 기능 만들어야함)
- 월별 거래내역 화면 구현
- 월별 거래내역 라우트 추가
- 거래내역 목록보기, 달력보기 컴포넌트화
- 거래내역 컴포넌트 생성

Feat : 월별거래내역, 상세정보 구현(수정, 삭제 미완성)

---

src/components/CalanderView.vue

style: claender css수정

---

src/api/index.js
src/pages/DetailPage.vue
src/stores/budget.js

fix: 거래 상세 페이지 수정

---

src/pages/DetailPage.vue
src/pages/MonthlyTransactionsPage.vue

- 거래상세 스타일 완성
- 월별거래내역 거래상세 띄우기

Feat: 거래상세 스타일, 월별 거래내역 거래상세 띄우기

---

src/pages/SettingImgPage.vue
src/pages/SettingPage.vue
src/pages/SettingProfilePage.vue

style: setting파일들 UI수정

---

src/components/SetGoalModal.vue

feat: 모달창 css 수정

---

src/pages/SettingPage.vue

Feat: 설정페이지 css 수정

---

src/pages/StatisticsPage.vue

Feat: 통계페이지 버튼 및 CSS 수정

---

index.html
src/App.vue
src/assets/main.css

style: font 수정

---

src/components/BottomNav.vue

feat: 하단 nav 초기 home설정 추가

---

src/components/AddTransactionModal.vue
src/components/CalanderView.vue

feat: CalanderView 거래내역 추가, addTransaction 하나 수정

---

package.json
src/components/SetGoalModal.vue

feat: 목표 금액 설정 유효성 검사

---

src/api/index.js
src/main.js
src/stores/goal.js

feat: 목표 수정 기능 추가

---

src/components/CalanderView.vue

Feat : 달력 CSS 수정

---

db.json

feat: db추가

---

src/components/AddTransactionModal.vue
src/pages/HomePage.vue

- AddTransactionModal.vue   CSS 수정
- HomePage.vue  CSS 수정

Feat: CSS 수정

---

src/pages/MonthlyTransactionsPage.vue

- MonthlyTransactionsPage.vue  날짜선택창 스크롤 가능하게 수정

Feat: 월별내역 날짜 스크롤 수정

---

src/pages/SettingImgPage.vue

feat: alert제거

---

src/components/SetGoalModal.vue
src/pages/GoalPage.vue

feat: 퍼센트랑 목표금액 입력 수정

---

src/components/SavingModal.vue
src/pages/GoalPage.vue

- GoalPage.vue  :  금액포맷팅 수정,  팝업효과 수정
- SavingModal.vue : 금액 포맷팅 수정

Feat : 목표페이지 수정완료

---

db.json

Feat : 데이터베이스 수정
